### ISSUE TITLE
License

### ISSUE THREAD

**Issue by abhinav-upadhyay** [philipperemy/n-beats#1]
Hi,

Thank you for implementing this model. I am interested in playing with it and was wondering about the license of it. Would be great if you could add a permissive license (MIT, BSD, Apache-2 etc) :)

**Comment by philipperemy** [comment]
Yeah MIT looks good ;)

**Comment by philipperemy** [comment]
Thanks for your interest btw. Keep in mind that I'm still working on it so it might not be 100% exact, although it looks quite promising.

**Comment by abhinav-upadhyay** [comment]
Thank you, I understand :)
