### ISSUE TITLE
Extra bias in Thetas calculation

### ISSUE THREAD

**Issue by Jolloniego** [philipperemy/n-beats#14]
Hey guys I think the θ calulcation in both models is being done incorrectly. 

Section 3.1 of the paper spcifies that: `θ = Linear(hid_4)` but in both models this is done with a fully connected or dense layer (i.e., has `bias=True` by default).

**Comment by philipperemy** [comment]
@Jolloniego good catch. It's being addressed in https://github.com/philipperemy/n-beats/pull/16.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/n-beats/commit/89ed79a5a9e1961e466ecaf59991ca8b2114a8f5 Merged!
