### ISSUE TITLE
Creating predictions on new data?

### ISSUE THREAD

**Issue by ddofer** [philipperemy/n-beats#24]
Are there any code snippets on using a trained model to get predictions on new data (where the labels are missing)? 
I'm unclear how to apply the model on new samples, where the actual labels/values are missing, given that the existing jupyter-notebook example is on labelled data, and uses it as part of the multiple prediction forecasts? 
Thanks!

**Comment by philipperemy** [comment]
Not at the moment but we can add them!

**Comment by philipperemy** [comment]
@ddofer I provided a very straightforward example on how to use it:

https://github.com/philipperemy/n-beats/blob/master/examples/simple_example.py

**Comment by sanseveroj** [comment]
I am struggling to get this solution to work with the pytorch model as there is no method for predicting? Any assistance here would be great, thanks!
