### ISSUE TITLE
Positional Argument error 

### ISSUE THREAD

**Issue by mfahadakbar** [philipperemy/n-beats#26]
Hi , 

when I run the model, it gives me this error

TypeError: __init__() takes from 4 to 6 positional arguments but 7 were given

![image](https://user-images.githubusercontent.com/19522276/77261619-2c110b80-6c66-11ea-8f4a-c0cf5d3f14f8.png)

**Comment by philipperemy** [comment]
@mfahadakbar this issue was fixed in https://github.com/philipperemy/n-beats/issues/25. Update your code and you'll be fine :)
