### ISSUE TITLE
Normalization Enquiry

### ISSUE THREAD

**Issue by ritchieng** [philipperemy/n-beats#3]
Thanks for open-sourcing your work.

I would like to clarify on your normalization procedure here: https://github.com/philipperemy/n-beats/blob/master/data.py#L21:L25

In deducting the `min` and dividing by the `max` of the variable `x` then subsequently splitting `x` into `x` and `y` where `y` is the target, there seems to be forward-looking of data of `y` as the normalization would have information contained from the target. 

In reality, it's not possible to normalize in this manner as you don't have the data from `y` part, which is from `backcast_length` onwards.

When you cycle through the data enough time, the network essentially can memorize the entire targets be in training, validation, or testing if you're using this method of normalization function. Which is why you see the ground truth matching the predictions.

**Comment by philipperemy** [comment]
@ritchieng yes you are correct. There's a small? forward-looking leak of the data in the target. How much does it help the model? I can't tell you exactly how much but I think it's fairly minimal. Feel free to open a PR to fix this :) Thanks for your question btw!

**Comment by andrewczgithub** [comment]
Hi @philipperemy @ritchieng how would we change code to remove the forward looking bias?
It should be only a few lines.

Many thanks,
Best,
Andrew

**Comment by philipperemy** [comment]
@andrewczgithub just compute all the constants on the train set and apply them on the test set. When we apply constants on the whole set and we split afterwards, then there's a forward looking bias.
