### ISSUE TITLE
How can I install a keras version backed by tensorflow-gpu?

### ISSUE THREAD

**Issue by lk1983823** [philipperemy/n-beats#30]
When I pip install the keras version. The system installed the tensorlow with cpu version. How can I install the gpu version?

**Comment by philipperemy** [comment]
Run this command:

```
pip uninstall -y tensorflow && pip install tensorflow-gpu
```

**Comment by lk1983823** [comment]
thanks

**Comment by ramdhan1989** [comment]
I got this error :
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-a06f40d36528> in <module>()
      6 import datetime
      7 from pandas.tseries.offsets import MonthEnd
----> 8 from nbeats_keras.model import NBeatsNet
      9 import matplotlib.pyplot as plt
     10 import seaborn as sns

c:\users\owner\anaconda3\envs\timeseries_dl_based\lib\site-packages\nbeats_keras\model.py in <module>()
      1 import numpy as np
----> 2 import tensorflow as tf
      3 # noinspection PyUnresolvedReferences
      4 import tensorflow.experimental.numpy as tnp
      5 from tensorflow.keras import backend as K

ModuleNotFoundError: No module named 'tensorflow'`

**Comment by philipperemy** [comment]
@ramdhan1989 probably `tensorflow` already contains the GPU binaries.

https://www.tensorflow.org/install/gpu

So just install `tensorflow` and it should work. If it's not working then there's a problem with your GPU setup.
