### ISSUE TITLE
Question on running trainer_pytorch.py

### ISSUE THREAD

**Issue by lk1983823** [philipperemy/n-beats#31]
When I run trainer_pytorch.py, I find that the thetas_dim for NBeatsNet.SEASONALITY_BLOCK is always equal to the forecast_length. For example, when forecast_length in the example is set to be 10, the second para in thetas_dims=[2, 8, 3] which is 8, will stay unchanged. It printed that:
```
| --  Stack Seasonality (#1) (share_weights_in_stack=False)
     | -- SeasonalityBlock(units=1024, thetas_dim=10, backcast_length=50, forecast_length=10, share_thetas=True) at @140649963671224
     | -- SeasonalityBlock(units=1024, thetas_dim=10, backcast_length=50, forecast_length=10, share_thetas=True) at @140649963669992
     | -- SeasonalityBlock(units=1024, thetas_dim=10, backcast_length=50, forecast_length=10, share_thetas=True) at @140649963669432
```
Analyzing the model.py, I find that in line 142, it uses forecast length to be the thetas_dim.
```
        else:
            super(SeasonalityBlock, self).__init__(units, forecast_length, device, backcast_length,
                                                   forecast_length, share_thetas=True)
```
so, is it an error? Thank you!

**Comment by philipperemy** [comment]
Regarding the seasonality block implementation:
You are perfectly right to notice that the thetas_dim element corresponding to a seasonality block would not be used (although it is used for both generic and trend blocks).
You are also right to notice that the by default we force the seasonality block to use the self.forecast_length (please have a look at the following discussion: https://github.com/philipperemy/n-beats/issues/29).

We still thought it was reasonable to have a thetas_dim of same dimensionality as the number of stacks even if the value for seasonality is not used.

**Comment by lk1983823** [comment]
Thank you so much.
