### ISSUE TITLE
Toy Example - Milk data set

### ISSUE THREAD

**Issue by sanseveroj** [philipperemy/n-beats#33]
The link provided for the toy example no longer has the data that I believe is being described. Could the link be updated?

**Comment by philipperemy** [comment]
@sanseveroj I forgot which example it refers to.
But you can find the data here: https://github.com/philipperemy/n-beats/blob/master/examples/data/milk.csv.
I hope it solves your issue! :)

**Comment by philipperemy** [comment]
You can find the link here: https://subhayo.wordpress.com/2019/05/15/time-series-analysis-of-monthly-milk-production/.
