### ISSUE TITLE
multivariate setup

### ISSUE THREAD

**Issue by rtrag** [philipperemy/n-beats#35]
@philipperemy 

What is the best approach for a multivariate time series like this?
https://www.tensorflow.org/tutorials/structured_data/time_series#part_2_forecast_a_multivariate_time_series

Can I just add more features to x? In the case of 2 features would have x.reshape(x.shape[0], x.shape[1], 2)?

**Comment by puzzlecollector** [comment]
I guess setting the input_dim value in the constructor of NBeatsNet should do it?

**Comment by philipperemy** [comment]
Yes set `input_dim=2` in the constructor of N-Beats!

**Comment by philipperemy** [comment]
The network expects a matrix of shape: `3D tensor with shape [batch, timesteps, feature]`.

**Comment by realiti4** [comment]
Pytorch implementation doesn't support input_dim I guess, is there a way to pass more than 1 feature?

**Comment by philipperemy** [comment]
Yes, use the Keras version at the moment. The Pytorch version mimicks the paper more by having input_dim=1.

**Comment by dervishson** [comment]
@philipperemy 
@puzzlecollector 
Is there anybody who used @puzzlecollector 's suggestion?
