### ISSUE TITLE
Keras import in Google Colab is falling

### ISSUE THREAD

**Issue by moritz-raabe** [philipperemy/n-beats#38]
I have read in another thread that the dependencies might be out of date. Could that be the problem that I am facing while trying to install the package in Google Colab? 

This is for pip install.
![image](https://user-images.githubusercontent.com/38106669/92301393-d99d8000-ef63-11ea-9813-dacaeaf349ed.png)

After I kind of managed to install it, I got the following error:
![image](https://user-images.githubusercontent.com/38106669/92301407-0487d400-ef64-11ea-9207-2666880dd53f.png)

Thanks in advance for your help! :)

**Comment by g0lemXIV** [comment]
For me install tensorflow 2.2.0 helped.

**Comment by philipperemy** [comment]
Yeah, I updated the dependencies. Try again.

**Comment by philipperemy** [comment]
(I pushed the nbeats 1.3.3 version that should solve this).
```bash
pip install nbeats-pytorch --upgrade
pip install nbeats-keras --upgrade
```
