### ISSUE TITLE
a question about milk examples

### ISSUE THREAD

**Issue by chenjw505** [philipperemy/n-beats#39]
in the data_generator code: 
```
def data_generator(x_full, y_full, bs):
    def split(arr, size):
        arrays = []
        while len(arr) > size:
            slice_ = arr[:size]
            arrays.append(slice_)
            arr = arr[size:]
        arrays.append(arr)
        return arrays
    while True:
        for rr in split((x_full, y_full), bs):
            yield rr
```

the parameters of function ’split‘ is ’(arr, size)‘,    but the actual is `split((x_full, y_full), bs)`, 

the (x_full, y_full) and  arr  is the same thing？

```while len(arr) > size ```  is always false， because arr=(x_full, y_full)， len(arr)=2,   but batch_size is  at least 10。
this means the examples always use full data to train model, not the batch data to train model

**Comment by philipperemy** [comment]
I think the function is buggy indeed!

**Comment by philipperemy** [comment]
https://github.com/philipperemy/n-beats/commit/5f86681ab2ba20c12d53b468a4b21d52c5abba74

**Comment by philipperemy** [comment]
I updated it.
