### ISSUE TITLE
Adding regressor or exogenous variable(s)

### ISSUE THREAD

**Issue by riyadparvez** [philipperemy/n-beats#4]
Is it possible to add features that would also take regressor or exogenous variables?

Stats-model version of adding exogenous variable: https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html

Facebook Prophet adding regressor: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

**Comment by andrewczgithub** [comment]
Hi @philipperemy !
Love this work!
Is the above a possibility, I know the original paper was for uni-variate series.
Best,
Andrew

**Comment by philipperemy** [comment]
Thanks guys! Yeah I agree it would be a great addition to N-beats :)

I don't have time at the moment but will put in mid term backlog!

**Comment by andrewczgithub** [comment]
Cheers @philipperemy ! much appreciated!
Best,
Andrew

**Comment by philipperemy** [comment]
@andrewczgithub There's an effort to support it here: https://github.com/philipperemy/n-beats/pull/12

**Comment by philipperemy** [comment]
cc @riyadparvez

**Comment by andrewczgithub** [comment]
Hi @philipperemy looking very cool!!
Will this be merged?
Cheers,
Andrew

**Comment by philipperemy** [comment]
@andrewczgithub it's now merged: https://github.com/philipperemy/n-beats/commit/f89f81f4cd60c206e0862d798b83d83ac849220e
Looking forward to hearing your feedbacks!
