### ISSUE TITLE
Data Leakage Question

### ISSUE THREAD

**Issue by StuartFarmer** [philipperemy/n-beats#40]
For the four image examples on the README.MD page, it looks as if the X and Y data have been normalized together before training. Is this true? 

If so, that would make the application of the model invalidated for any real-world applications where the future values are truly unbounded.

If not, what is the data preparation guideline for this model when bringing your own data?

**Comment by philipperemy** [comment]
@StuartFarmer which example exactly?

This one? https://github.com/philipperemy/n-beats#example.

**Comment by philipperemy** [comment]
I think you are referring to the notebook example (milk dataset).
I've updated it.
