### ISSUE TITLE
Is torchvision really a requirement?

### ISSUE THREAD

**Issue by jroakes** [philipperemy/n-beats#42]
I am having issues installing for Windows based on a requirement for torchvision.  

In the setup.py file, the following requirements are listed:

```
    INSTALL_REQUIRES.extend([
        'torch',
        'torchvision'
    ])
```

But I don't find any usage of torchvision in the code.  Is this really a needed requirement?

**Comment by philipperemy** [comment]
@jroakes sorry for the late reply. It's not necessary you are right. I am going to remove it from the deps.

**Comment by philipperemy** [comment]
Updated in https://github.com/philipperemy/n-beats/commit/e13239350de9a30d4c0689665f9b5ca3d5a19824
