### ISSUE TITLE
forward bias - normalization

### ISSUE THREAD

**Issue by andrewczgithub** [philipperemy/n-beats#5]
Hi @philipperemy @ritchieng how would we change code to remove the forward looking bias?
It should be only a few lines.

Many thanks,
Best,
Andrew

**Comment by philipperemy** [comment]
I made the fix. Going to push that tomorrow.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/n-beats/commit/f0e41255bdf39f6ce74f5974d335881e527eb3b3
