### ISSUE TITLE
The parameters 'exo_dim' and 'exo_shape' in the class 'NBeatsNet'

### ISSUE THREAD

**Issue by helonin** [philipperemy/n-beats#55]
Thanks for the great repository. I have a question: what is the parameters 'exo_dim' and 'exo_shape' in the class 'NBeatsNet' mean? How to use these extra variable?  Thanks for your help.

**Comment by philipperemy** [comment]
First of all thank you :)

Exogenous variables are external variables, useful in the training and predictions. They are fed along with the inputs.

![image](https://user-images.githubusercontent.com/4516927/149461700-1900e99f-5c7d-46ee-8c3b-2c4825fb9b9b.png)

I added an example on how to use them: 

- https://github.com/philipperemy/n-beats/blob/master/examples/exo_example.py

It should be much clearer for you. Let me know if you need extra help!
