### ISSUE TITLE
Can we use a pandas dataframe with multiple dependent variables?

### ISSUE THREAD

**Issue by thepraveen19** [philipperemy/n-beats#60]
I want to analyse the stock market data which has multiple parameters as input variables and one target variable.
Is it possible to use NBEATS ??

**Comment by philipperemy** [comment]
https://github.com/philipperemy/n-beats/issues/60

@thepraveen19 the original paper of NBeats only considered 1-D time series and the target was X[t+1] when the context was X[t], X[t-1]..., X[t-N]. 

Two points:
- But in practice, you don't need to have both X in the predictors and the target. 
- Also NBeats is a RNN but you technically don't need to use it as an RNN as well (you can forget the time dimension)

So it's definitely possible to use a Pandas DataFrame with multiple depend variables. 

A simple way to do that:

https://github.com/philipperemy/n-beats/blob/master/examples/pandas_example.py

**Comment by thepraveen19** [comment]
Hi,

Thank you for the revert. A quick question, you mentioned that we can
forget the time dimension. I don't understand how it works from the
statistical standpoint.
Is there a document or something that can help me understand how it
functions?

Your help is much appreciated.

Thank you

Regards,
Praveen

**Comment by philipperemy** [comment]
Hi,

I assumed that all the rows in the dataset are independent are permutable (meaning the order of your dataFrame does not matter). But if your dataset is indexed by time, yes we can take the time dimension into account. Let me work out another example for you.

**Comment by philipperemy** [comment]
Okay I updated the code here: https://github.com/philipperemy/n-beats/blob/master/examples/pandas_example.py

Including time.

**Comment by thepraveen19** [comment]
That is incredibly helpful...

I'm very grateful...

Thank you so much again ...

Regards,
Praveen

**Comment by philipperemy** [comment]
Welcome!

**Comment by thepraveen19** [comment]
Hi,

It gives an error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-993e57b1c820> in <module>()
      5       output_dim=1,
      6       nb_blocks_per_stack=1,
----> 7       backcast_length=timesteps)
      8 

TypeError: __init__() got an unexpected keyword argument 'output_dim'

I checked the documentation, 'output_dim' is not built in. How can I Solve this?
<img width="755" alt="Screenshot 2022-01-15 at 02 04 55" src="https://user-images.githubusercontent.com/42544315/149604850-187e1950-25f8-47af-a4d3-9fbc2a125590.png">

**Comment by philipperemy** [comment]
@thepraveen19  right I need to push the latest version. Hang on.

**Comment by philipperemy** [comment]
Run this and try again.
```
pip install nbeats-keras --upgrade
```

**Comment by thepraveen19** [comment]
Awesome! You are amaziiiiiing..... I went through your website( sky sense)... you are doing great work.... Cheers!

**Comment by philipperemy** [comment]
Awesome! Thanks for the feedback :)
