### ISSUE TITLE
Installation issue with tensor flow 2.5.0

### ISSUE THREAD

**Issue by thepraveen19** [philipperemy/n-beats#65]
Hi Philip,

Trying to pip install on my Mac m1. I get an error:

I use a Tensorflow 2.5.0 - is there a way to install NBEATS for Tf version 2.5.0?

The error is:

Collecting nbeats-keras
  Using cached nbeats_keras-1.7.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: numpy in /Users/praveen/miniforge3/lib/python3.9/site-packages (from nbeats-keras) (1.21.2)
  Using cached nbeats_keras-1.6.0-py3-none-any.whl (6.5 kB)
  Using cached nbeats_keras-1.5.0-py3-none-any.whl (6.4 kB)
  Using cached nbeats_keras-1.4.0-py3-none-any.whl (6.2 kB)
  Using cached nbeats_keras-1.3.4-py3-none-any.whl (5.9 kB)
  Using cached nbeats_keras-1.3.3-py3-none-any.whl (5.9 kB)
  Using cached nbeats_keras-1.3.1-py3-none-any.whl (5.3 kB)
Requirement already satisfied: matplotlib>=3.0 in /Users/praveen/miniforge3/lib/python3.9/site-packages (from nbeats-keras) (3.4.3)
Requirement already satisfied: pandas>=0.25.3 in /Users/praveen/miniforge3/lib/python3.9/site-packages (from nbeats-keras) (1.3.2)
  Using cached nbeats_keras-1.3.0-py3-none-any.whl (5.2 kB)
Collecting numpy==1.16.2
  Using cached numpy-1.16.2.zip (5.1 MB)
Collecting nbeats-keras
  Using cached nbeats_keras-1.2.0-py3-none-any.whl (4.9 kB)
  Using cached nbeats_keras-1.1.0-py3-none-any.whl (4.7 kB)
Collecting keras
  Using cached keras-2.8.0-py2.py3-none-any.whl (1.4 MB)
Collecting nbeats-keras
  Using cached nbeats_keras-1.0.0-py3-none-any.whl (4.3 kB)
[31mERROR: Cannot install nbeats-keras==1.0.0, nbeats-keras==1.1.0, nbeats-keras==1.2.0, nbeats-keras==1.3.0, nbeats-keras==1.3.1, nbeats-keras==1.3.3, nbeats-keras==1.3.4, nbeats-keras==1.4.0, nbeats-keras==1.5.0, nbeats-keras==1.6.0 and nbeats-keras==1.7.0 because these package versions have conflicting dependencies.[0m

The conflict is caused by:
    nbeats-keras 1.7.0 depends on tensorflow
    nbeats-keras 1.6.0 depends on tensorflow
    nbeats-keras 1.5.0 depends on tensorflow
    nbeats-keras 1.4.0 depends on tensorflow
    nbeats-keras 1.3.4 depends on tensorflow
    nbeats-keras 1.3.3 depends on tensorflow
    nbeats-keras 1.3.1 depends on tensorflow==2.0
    nbeats-keras 1.3.0 depends on tensorflow==2.0
    nbeats-keras 1.2.0 depends on tensorflow
    nbeats-keras 1.1.0 depends on tensorflow
    nbeats-keras 1.0.0 depends on tensorflow

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies[0m
[33mWARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/Users/praveenkadam/miniforge3/bin/python -m pip install --upgrade pip' command.[0m
Note: you may need to restart the kernel to use updated packages.

**Comment by philipperemy** [comment]
@thepraveen19 that is strange because TF2.5 is supported and tested in the continuous integration: https://github.com/philipperemy/n-beats/blob/60d52482c4a82b7de8e159dd9f780c7cdddd4616/tox.ini#L7

**Comment by philipperemy** [comment]
Try a fresh installation.

Also try to downgrade your pip:

```
pip install pip==21.3.1
```

Before re-installing. The new pip version can be some trouble to figure out dependencies sometimes.

**Comment by philipperemy** [comment]
Okay so I also have a new MacBookPro with M1 and it seems that tensorflow is not available for this platform....

**Comment by thepraveen19** [comment]
TF is not available via pip. It is doable via TF metal. There has been a recent update and I installed TF.
But I can't install NBEATs. Not sure how I go ahead.

https://developer.apple.com/metal/tensorflow-plugin/

**Comment by philipperemy** [comment]
I'm pretty sure it's because of that. I don't have much experience with TF metal. I need to dig a bit into that. But I won't be able to do it in the very short term. So if you can find a workaround in the mean time, please do it ;)

**Comment by ephsmith** [comment]
@thepraveen19, have you tried a manual install?  Pip was unable to resolve the dependencies in my case as well.  

My situation (version numbers) differs slightly from yours.  I have `tensorflow-metal`(0.4)  and `tensorflow-macos` (2.8.0) along with their dependencies and installed via Pip on an M1 Pro machine. 

I added the `n-beats_keras` directory on my Python path in an venv, ran unit tests successfully and am able to use the model.

**Comment by thepraveen19** [comment]
@ephsmith haven't tried manual install - I ran it on a windows machine, it went well. I will install the said versions and try it out. Thank you, I appreciate!

Cheers!
Praveen

**Comment by philipperemy** [comment]
You can also use Rosetta for MacOS on your terminal app. It worked for me. I'll close this issue for now since it's not directly related to N-Beats.
