### ISSUE TITLE
No module named 'nbeats_keras'

### ISSUE THREAD

**Issue by shathaa1983** [philipperemy/n-beats#66]
I downloaded the requirement library pip install nbeats-keras, but when I tried to import it, this error appeared
No module named 'nbeats_keras'.

Any help with this issue?
Thanks

**Comment by philipperemy** [comment]
@shathaa1983 did the pip install work?
```
virtualenv -p python3.10 venv && source venv/bin/activate
pip install nbeats-keras
python -c "from nbeats_keras.model import NBeatsNet as NBeatsKeras"
```
Works for me. Are you running on a New MacBook M1?
