### ISSUE TITLE
How to draw the picture in the paper?

### ISSUE THREAD

**Issue by lanhaoli** [philipperemy/n-beats#69]
How to draw the picture of "seasonal term" and "trend term" in the [paper?

**Comment by lanhaoli** [comment]
![Uploading 2022-09-05_183149.png…]()

**Comment by lanhaoli** [comment]
![2022-09-05_183149](https://user-images.githubusercontent.com/95955682/188429786-335a2b7b-6ad3-4c4e-a4dd-0d0539163b49.png)

**Comment by lanhaoli** [comment]
These are the pictures that I just uploaded. Thank you very much!

**Comment by lanhaoli** [comment]
May I ask if the code about N-Beats that you uploaded on Github includes the code for drawing the picture in the paper? I tried for a long time but couldn't find it. If you can reply to me, I will be very grateful! Looking forward to your reply.

**Comment by philipperemy** [comment]
@lanhaoli hey good question. You want it with pytorch or with keras?

**Comment by lanhaoli** [comment]
Thank you for your reply. I want to do that with PyTorch!

**Comment by philipperemy** [comment]
@lanhaoli how about this?

______________________________________________________________________________________________________

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4516927/193963101-fc0b8739-b300-4500-a741-d57e4c834f8e.png">

______________________________________________________________________________________________________

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/4516927/193963112-8fa4f80f-7d34-422c-8f7c-78a9e675fed1.png">

https://arxiv.org/pdf/1905.10437.pdf
Page 28.

**Comment by philipperemy** [comment]
New version uploaded: `1.8.0`

Refer to this example to generate the plots:

https://github.com/philipperemy/n-beats/blob/master/examples/interpretable_example.py
